/**
 * ID: ctst
 * Description: Category stock relation
 */
SET CLIENT_ENCODING = UTF8;
CREATE TABLE FS22 ( 
/*ID*/ CSID INTEGER , 
/*板块ID*/ CSCAID VARCHAR(16) , 
/*证券ID*/ CSSTID VARCHAR(16) , 
/*权重*/ CSWEIGHT DECIMAL(8,4) );
ALTER TABLE FS22 ADD CONSTRAINT FS22_PRIMARY PRIMARY KEY ( CSID );
ALTER TABLE FS22 ADD CONSTRAINT FS22_REFERENCE_1 FOREIGN KEY ( CSCAID ) REFERENCES FS21 ( CAID );
ALTER TABLE FS22 ADD CONSTRAINT FS22_REFERENCE_2 FOREIGN KEY ( CSSTID ) REFERENCES FS11 ( STID );
CREATE SEQUENCE FS22_CSID MINVALUE 0 START WITH 1;