/**
 * ID: mssg
 * Description: Message
 */
SET CLIENT_ENCODING = UTF8;
CREATE TABLE FS13 ( 
/*ID*/ MSID INTEGER , 
/*证券ID*/ MSSTID VARCHAR(16) , 
/*年份*/ MSYEAR SMALLINT , 
/*期间（自1）*/ MSPERIOD SMALLINT , 
/*序号*/ MSSEQ SMALLINT , 
/*发布日期*/ MSPUBLISH DATE , 
/*标题*/ MSSUBJECT VARCHAR(64) , 
/*内容*/ MSCONTENT VARCHAR(4096) );
ALTER TABLE FS13 ADD CONSTRAINT FS13_PRIMARY PRIMARY KEY ( MSID );
ALTER TABLE FS13 ADD CONSTRAINT FS13_UNIQUE_1 UNIQUE ( MSSTID , MSYEAR , MSPERIOD , MSSEQ );
ALTER TABLE FS13 ADD CONSTRAINT FS13_REFERENCE_1 FOREIGN KEY ( MSSTID ) REFERENCES FS11 ( STID );
CREATE SEQUENCE FS13_MSID MINVALUE 0 START WITH 1;