/**
 * ID: obup
 * Description: Object update audit trail
 */
SET CLIENT_ENCODING = UTF8;
CREATE TABLE FS90 ( 
/*ID*/ OBID INTEGER , 
/*对象ID*/ OBNAME VARCHAR(16) , 
/*任务开始*/ OBSTART TIMESTAMP , 
/*任务结束*/ OBEND TIMESTAMP );
ALTER TABLE FS90 ADD CONSTRAINT FS90_PRIMARY PRIMARY KEY ( OBID );
CREATE SEQUENCE FS90_OBID MINVALUE 0 START WITH 1;