/**
 * ID: favo
 * Description: Favorite stock
 */
SET CLIENT_ENCODING = UTF8;
CREATE TABLE FS91 ( 
/*证券ID*/ FASTID VARCHAR(16) );
ALTER TABLE FS91 ADD CONSTRAINT FS91_PRIMARY PRIMARY KEY ( FASTID );
ALTER TABLE FS91 ADD CONSTRAINT FS91_REFERENCE_1 FOREIGN KEY ( FASTID ) REFERENCES FS11 ( STID );