/**
 * ID: trdt
 * Description: Trading date
 */
SET CLIENT_ENCODING = UTF8;
CREATE TABLE FS02 ( 
/*ID*/ TRID INTEGER , 
/*交易所ID*/ TREXID VARCHAR(4) , 
/*交易日*/ TRDATE DATE );
ALTER TABLE FS02 ADD CONSTRAINT FS02_PRIMARY PRIMARY KEY ( TRID );
ALTER TABLE FS02 ADD CONSTRAINT FS02_UNIQUE_1 UNIQUE ( TREXID , TRDATE );
ALTER TABLE FS02 ADD CONSTRAINT FS02_REFERENCE_1 FOREIGN KEY ( TREXID ) REFERENCES FS01 ( EXID );
CREATE SEQUENCE FS02_TRID MINVALUE 0 START WITH 1;