/**
 * ID: fina
 * Description: Finance indicator
 */
SET CLIENT_ENCODING = UTF8;
CREATE TABLE FS12 ( 
/*ID*/ FIID INTEGER , 
/*证券ID*/ FISTID VARCHAR(16) , 
/*年份*/ FIYEAR SMALLINT , 
/*期间（自1）*/ FIPERIOD SMALLINT , 
/*状态*/ FISTATUS VARCHAR(1) , 
/*发布日期*/ FIPUBLISH DATE , 
/*股东权益合计(不含少数股东权益)*/ FINA DECIMAL(26,2) , 
/*营业收入*/ FIOI DECIMAL(26,2) , 
/*净利润(不含少数股东损益)*/ FINPE DECIMAL(26,2) , 
/*经营活动产生的现金流量净额*/ FIOCN DECIMAL(26,2) , 
/*年化营业收入-自动*/ FIOIY DECIMAL(26,2) , 
/*年化净利润(不含少数股东损益)-自动*/ FINPEY DECIMAL(26,2) , 
/*年化经营活动产生的现金流量净额-自动*/ FIOCNY DECIMAL(26,2) );
ALTER TABLE FS12 ADD CONSTRAINT FS12_PRIMARY PRIMARY KEY ( FIID );
ALTER TABLE FS12 ADD CONSTRAINT FS12_UNIQUE_1 UNIQUE ( FISTID , FIYEAR , FIPERIOD );
ALTER TABLE FS12 ADD CONSTRAINT FS12_REFERENCE_1 FOREIGN KEY ( FISTID ) REFERENCES FS11 ( STID );
CREATE SEQUENCE FS12_FIID MINVALUE 0 START WITH 1;