\i ./stock_create_trigger_std1.sql;
\i ./stock_create_trigger_fina.sql;

/**
     * ID: stck
     * Description: Stock master table
     */
CREATE VIEW VS11 AS SELECT 
/*证券代码*/ t0.STID STID , 
/*交易所ID*/ t0.STEXID STEXID , 
/*助记代码*/ t0.STCODE STCODE , 
/*名称*/ t0.STNAME STNAME , 
/*上市日期*/ t0.STLISTED STLISTED , 
/*退市日期*/ t0.STDELISTED STDELISTED , 
/*交易所名称*/ t1.EXNAME STEXNAME , 
/*上市天数*/ CASE WHEN t0.STDELISTED IS NULL THEN NOW()::DATE - t0.STLISTED::DATE ELSE NULL END STDAYS , 
/*动态市净率比率-手动*/ t0.STPBRATE STPBRATE , 
/*动态市净率排名-手动*/ t0.STPBRANK STPBRANK , 
/*动态市销率比率-手动*/ t0.STPSRATE STPSRATE , 
/*动态市销率排名-手动*/ t0.STPSRANK STPSRANK , 
/*动态市盈率比率-手动*/ t0.STPERATE STPERATE , 
/*动态市盈率排名-手动*/ t0.STPERANK STPERANK , 
/*动态市现率比率-手动*/ t0.STPCFRATE STPCFRATE , 
/*动态市现率排名-手动*/ t0.STPCFRANK STPCFRANK , 
/*连续盈利*/ COALESCE(t2.NPEL, 0) STNPEL , 
/*最近发布日期*/ t3.FIPUBLISH STPUBLISH , 
/*最近发布天数*/ NOW()::DATE - t3.FIPUBLISH::DATE STPUBLISHDAYS , 
/*最近年份*/ t3.FIYEAR STYEAR , 
/*最近期间(自1)*/ t3.FIPERIOD STPERIOD , 
/*消息标记*/ COALESCE(t4.MSYEAR > t3.FIYEAR OR t4.MSYEAR = t3.FIYEAR AND t4.MSPERIOD > t3.FIPERIOD, FALSE)::INT STMESSAGE , 
/*收藏标记*/ (t5.FASTID IS NOT NULL)::INT STFAVORITE FROM FS11 t0
LEFT JOIN FS01 t1 ON t1.EXID = t0.STEXID
LEFT JOIN (SELECT FISTID, COUNT(*) NPEL FROM FS12 t20 WHERE t20.FINPE > 0 AND NOT EXISTS (
  SELECT 1 FROM FS12 t21 WHERE t21.FISTID = t20.FISTID AND t21.FINPE < 0 AND (t21.FIYEAR > t20.FIYEAR OR t21.FIYEAR = t20.FIYEAR AND t21.FIPERIOD > t20.FIPERIOD)
  ) GROUP BY FISTID) t2 ON t2.FISTID = t0.STID
LEFT JOIN FS12 t3 ON t3.FISTID = t0.STID AND NOT EXISTS (SELECT 1 FROM FS12 t30 WHERE t30.FISTID = t3.FISTID AND (t30.FIYEAR > t3.FIYEAR OR t30.FIYEAR = t3.FIYEAR AND t30.FIPERIOD > t3.FIPERIOD))
LEFT JOIN FS13 t4 ON t4.MSSTID = t0.STID AND NOT EXISTS (SELECT 1 FROM FS13 t40 WHERE t40.MSSTID = t4.MSSTID AND (t40.MSYEAR > t4.MSYEAR OR t40.MSYEAR = t4.MSYEAR AND t40.MSPERIOD > t4.MSPERIOD))
LEFT JOIN FS91 t5 ON t5.FASTID = t0.STID;
